// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using one2many.Data;

namespace one2many.Migrations
{
    [DbContext(typeof(one2manyContext))]
    [Migration("20200428211721_initialmigration7")]
    partial class initialmigration7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("one2many.Models.Classinfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Classinfo");
                });

            modelBuilder.Entity("one2many.Models.Result", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Classinfoid")
                        .HasColumnType("int");

                    b.Property<int>("Studentid")
                        .HasColumnType("int");

                    b.Property<int>("meritpostion")
                        .HasColumnType("int");

                    b.Property<string>("term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("termresult")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Classinfoid");

                    b.HasIndex("Studentid");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("one2many.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("one2many.Models.Studentaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Classinfosid")
                        .HasColumnType("int");

                    b.Property<int?>("Resultsid")
                        .HasColumnType("int");

                    b.Property<int?>("Studentsid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Classinfosid");

                    b.HasIndex("Resultsid");

                    b.HasIndex("Studentsid");

                    b.ToTable("Studentaction");
                });

            modelBuilder.Entity("one2many.Models.Result", b =>
                {
                    b.HasOne("one2many.Models.Classinfo", "Classinfo")
                        .WithMany()
                        .HasForeignKey("Classinfoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("one2many.Models.Student", "Students")
                        .WithMany()
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("one2many.Models.Studentaction", b =>
                {
                    b.HasOne("one2many.Models.Classinfo", "Classinfos")
                        .WithMany()
                        .HasForeignKey("Classinfosid");

                    b.HasOne("one2many.Models.Result", "Results")
                        .WithMany()
                        .HasForeignKey("Resultsid");

                    b.HasOne("one2many.Models.Student", "Students")
                        .WithMany()
                        .HasForeignKey("Studentsid");
                });
#pragma warning restore 612, 618
        }
    }
}
